# Generated by Django 4.2.10 on 2025-03-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
