# Generated by Django 4.2.10 on 2025-03-03 00:07

from django.db import migrations, models
import rag_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_document_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[rag_app.models.validate_file_extension]),
        ),
    ]
